CREATE DATABASE aarya_school;
USE aarya_school;

CREATE TABLE admin(id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(50), password VARCHAR(50));
INSERT INTO admin(username,password) VALUES('admin','admin');

CREATE TABLE students(id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100));
CREATE TABLE teachers(id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100));
CREATE TABLE attendance(id INT AUTO_INCREMENT PRIMARY KEY, student VARCHAR(100), status VARCHAR(20));
CREATE TABLE fees(id INT AUTO_INCREMENT PRIMARY KEY, student VARCHAR(100), amount INT);
